apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: e-jotter-deployment
  name: e-jotter-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30008
  selector:
    app: e-jotter-deployment
status:
  loadBalancer: {}
